### ISSUE TITLE
SubscriptionPaymentBehaviour not exposed properly

### ISSUE THREAD

**Issue by Skydive** [arlyon/async-stripe#306] opened 2022-11-30 14:09 UTC
### Describe the bug

I'm getting a nasty compiler error while compiling. I'm trying to set the `payment_behaviour` field of a new subscription as documented in the [stripe guide](https://stripe.com/docs/billing/subscriptions/build-subscriptions?ui=elements#create-subscription). 

```
Error[E308] mismatched types
expected enum `stripe::generated::billing::subscription::SubscriptionPaymentBehavior`,
found enum `stripe::SubscriptionPaymentBehavior`
```

I can also see in the automatically [generated API documentation](https://docs.rs/async-stripe/latest/stripe/struct.CreateSubscription.html), there is something wrong in the ``CreateSubscription`` struct. I cannot access the ``SubscriptionPaymentBehaviour`` struct from it. Perhaps this is related to the problem I have.

### To Reproduce

Fetch latest version of async-stripe from github.
Attempt to set the `payment_behaviour` field of a `CreateSubscription` struct.

### Expected behavior

Expecting normal compilation

### Code snippets

```rust
let mut params = CreateSubscription::new(customer.id);
params.items = Some(vec![CreateSubscriptionItems {
    price: Some(data.price_id.to_owned()),
    ..Default::default()
}]);
params.payment_settings = Some(CreateSubscriptionPaymentSettings {
    save_default_payment_method: Some(CreateSubscriptionPaymentSettingsSaveDefaultPaymentMethod::OnSubscription),
    ..Default::default()
});
params.payment_behavior = Some(SubscriptionPaymentBehavior::DefaultIncomplete); // <------
params.expand = &["latest_invoice.payment_intent"];
Subscription::create(&STRIPE_CLIENT, params).await
```

**Cargo.toml**
```toml
[dependencies]
async-stripe = { git = "https://github.com/arlyon/async-stripe", default-features = false, features = ["runtime-tokio-hyper", "billing", "checkout"]}
```

### OS

Linux 6.0.2

### Rust version

rustc 1.65.0 (897e37553 2022-11-02)

### Library version

async-stripe (latest, branch master & 0.15.0)

### API version

2022-11-15

**Comment by arlyon** [comment] 2022-12-07 13:30
Hi, we have an issue with name clashing which is detailed in this issue: https://github.com/arlyon/async-stripe/issues/154.

You should be able to just import the appropriate variant from the generated module directly.

**Comment by arlyon** [comment] 2022-12-07 13:33
I am going to close this with the expectation that it is a duplicate of the above issue. If that is not the case, please leave a comment :)

**Closed by arlyon** 2022-12-07 13:33 UTC
Labels: bug
