### ISSUE TITLE
Can't use SubscriptionProrationBehavior

### ISSUE THREAD

**Issue by normano** [arlyon/async-stripe#256] opened 2022-07-31 22:32 UTC
Not sure why I can't use it as it seems to be defined in one file. Removing "checkout" or "billing" will break resources/generated/quote.rs.

Cargo.toml
async-stripe = { version = "^0.15", default-features = false, features = ["runtime-tokio-hyper", "checkout", "billing"] }

Error
error[E0308]: mismatched types
 update_sub_params.proration_behavior = Some(stripe::SubscriptionProrationBehavior::AlwaysInvoice);
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `stripe::resources::generated::billing::subscription::SubscriptionProrationBehavior`, found enum `SubscriptionProrationBehavior`

**Comment by arlyon** [comment] 2022-08-15 14:37
So, there are a known number of 'repeat definitions' where the same struct is defined in the openapi spec multiple times with the same generated name. This seems to be one of those cases.

**Comment by arlyon** [comment] 2022-08-15 14:38
This issue (https://github.com/arlyon/async-stripe/issues/154) has some more context.

**Comment by arlyon** [comment] 2022-11-17 11:05
I am closing this now, as the issue is partially addressed in #296 and #154 is the tracking issue.

**Closed** 2022-11-17 11:06 UTC
