### ISSUE TITLE
Adding UsageRecord

### ISSUE THREAD

**Issue by FSMaxB** [arlyon/async-stripe#213] opened 2022-04-19 10:35 UTC
What would be involved in exposing [`UsageRecord`](https://stripe.com/docs/api/usage_records). I can see that it is already included in the generated code (as mentioned in https://github.com/arlyon/async-stripe/issues/32 as well), but both a `create` method and the necessary `CreateUsageRecord` parameter haven't been automatically generated from the looks of it.

Can this be added by providing the `CreateUsageRecord` in a new `resources::usage_record_ext` or does the code generation need to be updated for this to work?

In case of the former, I would be willing to create a pull request to add support.

From my understanding that would involve:
* Adding a `def_id` macro invocation for adding a `UsageRecordId` type.
* Adding the necessary `use` statements for the generated `usage_record.rs`.
* Implement a `UsageRecordAction` enum and a `CreateUsageRecord` parameter type
* Implementing `UsageRecord::create`.

**Comment by arlyon** [comment] 2022-04-21 20:41
Hi! Thanks for getting in touch, always great to find holes in the API and I think this is a fun task. So, I did some digging and currently the codegen doesn't support a number of request types, one of which is creating resources that are 'sub-resources' of another. 

Full list:
```shell
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/bank_accounts    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/bank_accounts/{id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Account: /v1/accounts/{account}/bank_accounts/{id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/capabilities/{capability}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/external_accounts    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/external_accounts/{id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Account: /v1/accounts/{account}/external_accounts/{id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/login_links    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/people    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/people/{person}    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Account: /v1/accounts/{account}/people/{person}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/persons    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/persons/{person}    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Account: /v1/accounts/{account}/persons/{person}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Account: /v1/accounts/{account}/reject    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for ApplicationFee: /v1/application_fees/{fee}/refunds/{id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for ApplicationFee: /v1/application_fees/{id}/refund    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for ApplicationFee: /v1/application_fees/{id}/refunds    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Charge: /v1/charges/{charge}/capture    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Charge: /v1/charges/{charge}/dispute    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Charge: /v1/charges/{charge}/dispute/close    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Charge: /v1/charges/{charge}/refund    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Charge: /v1/charges/{charge}/refunds    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Charge: /v1/charges/{charge}/refunds/{refund}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for CheckoutSession: /v1/checkout/sessions/{session}/expire    
WARN stripe_openapi_codegen::codegen: CountrySpecSupportedBankAccountCurrencies has no properties ({"additionalProperties":{"items":{"maxLength":5000,"type":"string"},"type":"array"},"description":"Currencies that can be accepted in the specific country (for transfers).","type":"object"})    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for CreditNote: /v1/credit_notes/{id}/void    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/balance_transactions    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/balance_transactions/{transaction}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/bank_accounts    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/bank_accounts/{id}/verify    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/cards    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Customer: /v1/customers/{customer}/discount    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/sources    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/sources/{id}/verify    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/subscriptions    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/subscriptions/{subscription_exposed_id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Customer: /v1/customers/{customer}/subscriptions/{subscription_exposed_id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Customer: /v1/customers/{customer}/subscriptions/{subscription_exposed_id}/discount    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Customer: /v1/customers/{customer}/tax_ids    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Customer: /v1/customers/{customer}/tax_ids/{id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Dispute: /v1/disputes/{dispute}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Dispute: /v1/disputes/{dispute}/close    
WARN stripe_openapi_codegen::codegen: ExchangeRateRates has no properties ({"additionalProperties":{"type":"number"},"description":"Hash where the keys are supported currencies and the values are the exchange rate at which the base id currency converts to the key currency.","type":"object"})    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for File: /v1/files    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Invoice: /v1/invoices/{invoice}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Invoice: /v1/invoices/{invoice}/finalize    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Invoice: /v1/invoices/{invoice}/mark_uncollectible    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Invoice: /v1/invoices/{invoice}/pay    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Invoice: /v1/invoices/{invoice}/send    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Invoice: /v1/invoices/{invoice}/void    
WARN stripe_openapi_codegen::codegen: NotificationEventDataPreviousAttributes has no properties ({"description":"Object containing the names of the attributes that have changed, and their previous values (sent along only with *.updated events).","type":"object"})    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Order: /v1/orders/{id}/pay    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Order: /v1/orders/{id}/returns    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for PaymentIntent: /v1/payment_intents/{intent}/apply_customer_balance    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for PaymentIntent: /v1/payment_intents/{intent}/cancel    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for PaymentIntent: /v1/payment_intents/{intent}/capture    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for PaymentIntent: /v1/payment_intents/{intent}/confirm    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for PaymentIntent: /v1/payment_intents/{intent}/verify_microdeposits    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for PaymentMethod: /v1/payment_methods/{payment_method}/attach    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for PaymentMethod: /v1/payment_methods/{payment_method}/detach    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Payout: /v1/payouts/{payout}/cancel    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Payout: /v1/payouts/{payout}/reverse    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Plan: /v1/plans    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for PromotionCode: /v1/promotion_codes    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Quote: /v1/quotes    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Quote: /v1/quotes/{quote}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Quote: /v1/quotes/{quote}/accept    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Quote: /v1/quotes/{quote}/cancel    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Quote: /v1/quotes/{quote}/finalize    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Refund: /v1/refunds/{refund}/cancel    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Review: /v1/reviews/{review}/approve    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for SetupIntent: /v1/setup_intents/{intent}/cancel    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for SetupIntent: /v1/setup_intents/{intent}/confirm    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for SetupIntent: /v1/setup_intents/{intent}/verify_microdeposits    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Source: /v1/sources/{source}/verify    
WARN stripe_openapi_codegen::codegen: encountered unhandled DELETE for Subscription: /v1/subscriptions/{subscription_exposed_id}/discount    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for SubscriptionSchedule: /v1/subscription_schedules/{schedule}/cancel    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for SubscriptionSchedule: /v1/subscription_schedules/{schedule}/release    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Topup: /v1/topups    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Topup: /v1/topups/{topup}/cancel    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Transfer: /v1/transfers/{id}/reversals    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for Transfer: /v1/transfers/{transfer}/reversals/{id}    
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for UsageRecord: /v1/subscription_items/{subscription_item}/usage_records
```

The one we are interested in is obviously the last one: 

```
WARN stripe_openapi_codegen::codegen: encountered unhandled POST for UsageRecord: /v1/subscription_items/{subscription_item}/usage_records
```

The crux of the issue is that in https://github.com/arlyon/async-stripe/blob/40ed9a3798fc10dc35fd688272c6becc5f51a778/openapi/src/codegen.rs#L1449-L1583 we only handle the case in create where there are no parameters, while `usage_records` has 1 parameter, namely the `subscription_item` in the path.

I would like to provide a fix for this (and others in the same situation) but in the mean time if you'd like to write a PR for the extension service it would be more than welcome as a stop-gap (with the caveat that it may be replaced).

**Comment by arlyon** [comment] 2022-04-28 14:18
In response to the PR, I am renaming this issue to cover the broader case

**Closed** 2022-04-28 14:42 UTC
