### ISSUE TITLE
Deserialization error when creating a SetupIntent on a connected account

### ISSUE THREAD

**Issue by Canop** [arlyon/async-stripe#183] opened 2022-03-16 15:38 UTC
I create the stripe Client for a connected account:

        let mut stripe_client = stripe::Client::new(&stripe_configuration.sk_key);
        stripe_client.set_stripe_account(&connected_account.id);

This works well for some function but it fails when I try to do this:

        let stripe_customer = stripe::CustomerId::from_str(stripe_customer_id)?;
        ...
        let setup_intent = stripe::SetupIntent::create(&self.stripe_client, params).await?;

I get this error:

    Err(
        JSONSerialize(
            Error("data did not match any variant of untagged enum Expandable", line: 4, column: 54),
        ),
    )

This is due to a failure deserializing the `application` field, whose value is a string, in the response.

I checked that by removing the `application` field from the `SetupIntent` struct the problem disappears.

Is that a bug ? Or do I do something wrong ?

**Comment by arlyon** [comment] 2022-03-18 10:06
Hi! What version of the library are you using? We have a number of sweeping changes that will be released very soon and the version on crates is quite old.

**Comment by Canop** [comment] 2022-03-18 13:22
I tried both with 0.13 and the current master (by forking it).

**Comment by arlyon** [comment] 2022-03-18 13:30
I use discussions to post the general roadmap: https://github.com/arlyon/async-stripe/discussions

You may be in these threads: 
- https://github.com/arlyon/async-stripe/discussions/139
- https://github.com/arlyon/async-stripe/discussions/186

Let me know if you think anything is unclear or missing

**Comment by arlyon** [comment] 2022-03-18 13:40
The issue is that the 'Expandable' type expects a know Id type for Application, which we do not have in `ids.rs`, meaning the Id type is a unit:

https://github.com/arlyon/async-stripe/blob/1319a71a0d0d738559f3502ec7c091cd965e8c2d/src/resources/generated/application.rs#L17-L23

Putting this type in would fix the issue, so could you share with me what the value of the string you're trying to deserialize is?

**Comment by Canop** [comment] 2022-03-18 13:48
The SetupIntent object which makes async-stripe deserialization fails looks like this:

```
{
  "id": "seti_1Keglflfelnr5z88r7xYNkvvv",
  "object": "setup_intent",
  "application": "ca_KMfoL45rtySU85Q8b9Z87trrfUdWeeA",
  "cancellation_reason": null,
  "client_secret": "seti_1Keglflfelnr5z88r7xYNkvvv_secret_LLMllvmPSLgSy6KboumKuDMcBWtruc",
  "created": 1647611136,
  "customer": "cus_LLMllvmPSLgSy6Kb",
  "description": null,
  "last_setup_error": null,
  "latest_attempt": null,
  "livemode": false,
  "mandate": null,
  "metadata": {},
  "next_action": null,
  "on_behalf_of": null,
  "payment_method": null,
  "payment_method_options": {
    "card": {
      "mandate_options": null,
      "request_three_d_secure": "automatic"
    }
  },
  "payment_method_types": [
    "card"
  ],
  "single_use_mandate": null,
  "status": "requires_payment_method",
  "usage": "off_session"
}
```

**Comment by arlyon** [comment] 2022-03-18 14:19
Yes, but having looked at the stripe openapi spec, `application` doesn't have an `x-resourceId` field which to me seems like an issue on their end. I'll get in touch with someone at stripe and ask them to advise. You may be able to solve the issue in the mean time by adding the Id and overriding the id type in the above snippet, and I'll get back to you.

**Comment by arlyon** [comment] 2022-03-18 15:25
So, fairly quick response. The solution is that the heuristic we use to determine 'expandible things' is wrong. The guy in the issue above gave some advice on how they do it internally which we will model ours on, and will fix the remaining cases where things have ids but no `x-resourceId`

```
2022-03-18T15:22:26.842125Z  WARN stripe_openapi_codegen::metadata: application has an id field but no x-resourceId    
2022-03-18T15:22:26.843668Z  WARN stripe_openapi_codegen::metadata: connect_collection_transfer has an id field but no x-resourceId    
2022-03-18T15:22:26.844393Z  WARN stripe_openapi_codegen::metadata: deleted_alipay_account has an id field but no x-resourceId    
2022-03-18T15:22:26.844563Z  WARN stripe_openapi_codegen::metadata: deleted_bank_account has an id field but no x-resourceId    
2022-03-18T15:22:26.844602Z  WARN stripe_openapi_codegen::metadata: deleted_bitcoin_receiver has an id field but no x-resourceId    
2022-03-18T15:22:26.844647Z  WARN stripe_openapi_codegen::metadata: deleted_card has an id field but no x-resourceId    
2022-03-18T15:22:26.845115Z  WARN stripe_openapi_codegen::metadata: deleted_price has an id field but no x-resourceId    
2022-03-18T15:22:26.851982Z  WARN stripe_openapi_codegen::metadata: platform_tax_fee has an id field but no x-resourceId    
2022-03-18T15:22:26.853542Z  WARN stripe_openapi_codegen::metadata: reserve_transaction has an id field but no x-resourceId    
2022-03-18T15:22:26.857016Z  WARN stripe_openapi_codegen::metadata: tax_deducted_at_source has an id field but no x-resourceId
```

I'll write a fix if I get time this weekend. Hopefully the patch I recommended will cover your requirements until then!

**Closed** 2022-03-18 17:53 UTC

**Comment by Canop** [comment] 2022-03-25 06:49
I checked it's OK with release 0.14, thanks.
